name:                ffi-export-lib
version:             0.1.0.0
github:              "githubuser/symkell"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

language: GHC2021

default-extensions:
- LambdaCase
- OverloadedStrings
- ForeignFunctionInterface

ghc-options:
- -Wall
- -fPIC
- -flink-rts

dependencies:
- base >= 4.18 && < 4.22
- symkellCore
- text >= 2.0 && < 2.2
- text-show >= 3.10 && < 3.12

library:
  source-dirs: src
  include-dirs: include
  exposed-modules:
  - FFIExport 