name:                symkell
version:             0.1.0.0
github:              "githubuser/symkell"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"



tested-with: GHC == 9.12.1 || == 9.10.1 || == 9.8.4 || == 9.6.6

language: GHC2021

default-extensions:
- LambdaCase
- OverloadedStrings

ghc-options:
- -Wall

dependencies:
- ad >= 4.5 && < 4.6
- base >= 4.18 && < 4.22
- containers >= 0.6 && < 0.8
- deepseq >= 1.4 && < 1.6
- text >= 2.0 && < 2.2
- text-show >= 3.10 && < 3.12
- bytestring    

library:
  source-dirs: src
  ghc-options:
    - -stubdir autogen-stubs
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N 


foreign-libraries:
  - name: symkell-ffi  
    type: native-shared
    language: C         
    ghc-options:
      - -shared         
      - -dynamic        
      - -fPIC           
      - -flink-rts      
      - -XForeignFunctionInterface 
      - -o libsymkell-ffi.so
    exposed-modules:
      - Symkell.FFI
    dependencies:
      - base
      - symkell       
      - bytestring    
      - text          



tests:
  symkell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symkell
    - hspec >= 2.7 && < 2.12
    - QuickCheck >= 2.14 && < 2.15

